# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authors.Author')),
            ],
        ),
    ]
